### Create Report request
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "mileage": 10000,
    "lng": 0,
    "lat": 0,
    "price": 50000
}

### Approve an existing report
PATCH http://localhost:3000/reports/7
Content-Type: application/json

{
    "approved": true
}

### Get an estmate for an exisiting vehicle
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=10000&year=1980